### ISSUE TITLE
thermostat permanently set to be off

### ISSUE THREAD

**Issue by Letmeload** [DenisMtfl/node-red-contrib-dynamic-thermostat#30]
If the current temperature is changing the switch topic always will be set to true.

A function that the thermostat permanently set to be off would be fine.

**Comment by Caprico85** [comment]
I've sent a pull request (#45), which fixes the thermostat and provides this function.

If my PR gets accepted, you can send a message like
```json
{
    "topic": "switch",
    "payload": false
}
```
to have the thermostat permanently stay off. And later send a message
```json
{
    "topic": "switch",
    "payload": "auto"
}
```
to switch it back into automatic mode.
