### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by cheechie** [DenisMtfl/node-red-contrib-dynamic-thermostat#33]
It seems that this is not working anymore.  The onoff state does not change regardless if the current temp is higher or lower than the set temp.

![image](https://user-images.githubusercontent.com/49294767/148701071-e016bfdb-3ff7-47ee-b3d4-1b29feeb8638.png)

**Comment by DenisMtfl** [comment]
Yes I'm working on it...

**Comment by WeterPeter** [comment]
> Yes I'm working on it...

It is now march 2022 and still not working.
When will it?

**Comment by Caprico85** [comment]
I have send pull request #45 with my changes to fix this.

**Comment by DenisMtfl** [comment]
Thanks für the PR @Caprico85, i have created a new version 0.0.9. 
#48
